MvcBlog/MvcBlog/Controllers/AdminMakaleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcBlog.Models;
using System.Web.Helpers;
using System.IO;
using PagedList;
using PagedList.Mvc;

namespace MvcBlog.Controllers
{
    public class AdminMakaleController : Controller
    {
        MvcBlogDB db = new MvcBlogDB();

       
        public ActionResult Index(int page = 1)
        {
            var makales = db.Makales.OrderByDescending(m => m.MakaleID).ToPagedList(page,10);           
            return View(makales);
        }

        
        public ActionResult Details(int id)
        {
            return View();
        }

        
        public ActionResult Create()
        {
            ViewBag.KategoriID = new SelectList(db.Kategoris, "KategoriID", "KategoriAdi");
            return View();
        }

        
        [HttpPost]
        public ActionResult Create(Makale makale, string etiketler, HttpPostedFileBase foto)
        {
            if (ModelState.IsValid)
            {
                if (foto != null)
                {
                    WebImage img = new WebImage(foto.InputStream);
                    FileInfo fotoinfo = new FileInfo(foto.FileName);
                    string newfoto = Guid.NewGuid().ToString() + fotoinfo.Extension;
                    img.Resize(800, 350);
                    img.Save("~/Upload/MakaleFoto/" + newfoto);
                    makale.Foto = "/Upload/MakaleFoto/" + newfoto;

                }
                if (etiketler != null)
                {
                    string[] etiketdizi = etiketler.Split(',');
                    foreach (var item in etiketdizi)
                    {
                        var yenietiket = new Etiket { EtiketAdi = item };
                        db.Etikets.Add(yenietiket);
                        makale.Etikets.Add(yenietiket);
                    }
                }

                makale.UyeID = Convert.ToInt32(Session["UyeID"]);
                makale.Okunma = 0;
                db.Makales.Add(makale);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(makale);
        }

        
        public ActionResult Edit(int id)
        {
            var makale = db.Makales.Where(m => m.MakaleID == id).SingleOrDefault();
            if (makale == null)
            {
                return HttpNotFound();
            }
            ViewBag.KategoriID = new SelectList(db.Kategoris, "KategoriID", "KategoriAdi", makale.KategoriID);
            return View(makale);
        }

       
        [HttpPost]
        public ActionResult Edit(int id, HttpPostedFileBase foto, Makale makale)
        {
            // burada try catch bloklarını görmül olduk
            try
            {
                var GuncellenecekMakale = db.Makales.Where(m => m.MakaleID == id).SingleOrDefault();

                if (foto != null)
                {
                    if (System.IO.File.Exists(Server.MapPath(GuncellenecekMakale.Foto)))
                    {
                        System.IO.File.Delete(Server.MapPath(GuncellenecekMakale.Foto));
                    }

                    WebImage img = new WebImage(foto.InputStream);
                    FileInfo fotoinfo = new FileInfo(foto.FileName);

                    string newfoto = Guid.NewGuid().ToString() + fotoinfo.Extension;
                    img.Resize(800, 350);
                    img.Save("~/Upload/MakaleFoto/" + newfoto);
                    GuncellenecekMakale.Foto = "/Upload/MakaleFoto/" + newfoto;
                    GuncellenecekMakale.Baslik = makale.Baslik;
                    GuncellenecekMakale.Icerik = makale.Icerik;
                    GuncellenecekMakale.KategoriID = makale.KategoriID;
                    GuncellenecekMakale.Tarih = makale.Tarih;
                    db.SaveChanges();                  
                }
                else
                {
                    GuncellenecekMakale.Baslik = makale.Baslik;
                    GuncellenecekMakale.Icerik = makale.Icerik;
                    GuncellenecekMakale.KategoriID = makale.KategoriID;
                    GuncellenecekMakale.Tarih = makale.Tarih;
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        
        public ActionResult Delete(int id)
        {
            var makale = db.Makales.Where(m => m.MakaleID == id).SingleOrDefault();
            if (makale == null)
            {
                return HttpNotFound();
            }
            return View(makale);
        }

        
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                var makale = db.Makales.Where(m => m.MakaleID == id).SingleOrDefault();

                if (makale == null)
                {
                    return HttpNotFound();
                }
                if (System.IO.File.Exists(Server.MapPath(makale.Foto)))
                {
                    System.IO.File.Delete(Server.MapPath(makale.Foto));
                }
                foreach (var item in makale.Yorums.ToList())
                {
                    db.Yorums.Remove(item);
                }
                foreach (var item in makale.Etikets.ToList())
                {
                    db.Etikets.Remove(item);
                }
                db.Makales.Remove(makale);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MvcBlog/MvcBlog/Views/AdminMakale/Create.cshtml
@model MvcBlog.Models.Makale

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@using (Html.BeginForm("Create", "AdminMakale", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Makale Oluştur</h4>
        <hr />

        <div class="form-group">
            @Html.Label("KategoriID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("KategoriID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.KategoriID, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Başlık", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Baslik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Baslik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("İçerik", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Icerik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Icerik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Foto", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="foto" id="foto" accept=".jpg,.png,.gif,.JPEG,.jpeg" class="form-control"/>
                @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Tarih", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tarih, new { htmlAttributes = new { @class = "form-control", @type="date" } })
                @Html.ValidationMessageFor(model => model.Tarih, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.Label("Etiketler", new { @class="control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.TextBox("Etiketler")*@
                <input type="text" id="Etiketler" name="Etiketler" data-role="tagsinput" class="bootstrap-tagsinput"/>
            </div>
        </div>        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input style="cursor:pointer" type="submit" value="Kaydet" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Geri Dön", "Index")
</div>

MvcBlog/MvcBlog/Views/AdminMakale/Delete.cshtml
@model MvcBlog.Models.Makale

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h3 style="color:red">Makaleyi silmeyi onaylıyor musunuz?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.Label("Kategori Adı")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kategori.KategoriAdi)
        </dd>

        <dt>
            @Html.Label("Başlık")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Baslik)
        </dd>

        <dt>
            @Html.Label("İçerik")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Icerik)
        </dd>

        <dt>
            @Html.Label("Foto")
        </dt>

        <dd>
            <img width="150" src="@Model.Foto" alt="Alternate Text"/>
        </dd>

        <dt>
            @Html.Label("Tarih")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tarih)
        </dd>

        <dt>
            @Html.Label("ÜyeID")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UyeID)
        </dd>

        <dt>
            @Html.Label("Okunma")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Okunma)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input style="cursor:pointer" type="submit" value="Sil" class="btn btn-danger" /> |
            @Html.ActionLink("Geri Dön", "Index")
        </div>
    }
</div>

MvcBlog/MvcBlog/Views/AdminMakale/Edit.cshtml
@model MvcBlog.Models.Makale

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@using (Html.BeginForm("Edit", "AdminMakale", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Makale Düzenle</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MakaleID)

        <div class="form-group">
            @Html.Label("Başlık", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Baslik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Baslik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("İçerik", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Icerik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Icerik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Eski Foto", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img width="75" src="@Model.Foto" alt="Alternate Text"/>
                @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Yeni Foto", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="foto" id="foto" accept=".jpg,.png,.gif,.JPEG,.jpeg" class="form-control" />
                @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Tarih", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tarih, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                @Html.ValidationMessageFor(model => model.Tarih, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("KategoriID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("KategoriID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.KategoriID, "", new { @class = "text-danger" })
            </div>
        </div>  

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input style="cursor:pointer" type="submit" value="Kaydet" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Geri Dön", "Index")
</div>

MvcBlog/MvcBlog/Views/AdminMakale/Index.cshtml
@model IPagedList<MvcBlog.Models.Makale>
@using PagedList;
@using PagedList.Mvc;

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Makaleler</h2>

<p>
    @Html.ActionLink("Yeni Makale", "Create", null, new { @class = "btn btn-success" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.Label("KategoriAdı")
        </th>
        <th>
            @Html.Label("Başlık")
        </th>
        <th>
            @Html.Label("Foto")
        </th>
        <th>
            @Html.Label("Tarih")
        </th>
        <th>
            @Html.Label("Okunma")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Kategori.KategoriAdi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Baslik)
        </td>
        <td>
            <img width="75" src="@item.Foto"/>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Tarih)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Okunma)
        </td>
        <td>
            @Html.ActionLink("Düzenle", "Edit", new { id=item.MakaleID }, new { @class = "btn btn-info" }) |         
            @Html.ActionLink("Sil", "Delete", new { id=item.MakaleID }, new { @class = "btn btn-danger" })
        </td>
    </tr>
}

</table>

<div class="row">
    <div class="col-md-8 text-center">
        <div class="pagedList pagination-lg">
            @Html.PagedListPager(Model, Page => Url.Action("Index", new { Page }), PagedListRenderOptions.Classic)
        </div>
    </div>
</div>